# Generated by Django 3.0.4 on 2020-04-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200417_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='suppliers',
            name='population',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
