# Generated by Django 3.0.5 on 2020-04-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200417_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citys',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='population',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='population',
        ),
        migrations.AddField(
            model_name='citys',
            name='region',
            field=models.CharField(default=123, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citys',
            name='city_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Citys'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Citys'),
        ),
    ]
