# Generated by Django 3.0.5 on 2020-04-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200417_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citys',
            name='region',
            field=models.CharField(choices=[('A', 'Akdeniz'), ('DA', 'Dogu Anadolu'), ('E', 'Ege'), ('GA', 'Guneydogu Anadolu'), ('IA', 'Ic Anadolu'), ('M', 'Marmara'), ('K', 'Karadeniz')], max_length=50),
        ),
    ]
