# Generated by Django 3.0.5 on 2020-04-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200417_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='supplier',
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_id',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customers', verbose_name='customer_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='customer_id',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customers', verbose_name='customer_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='supplier_id',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Suppliers', verbose_name='supplier_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Citys', verbose_name='customer_name'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Citys', verbose_name='supplier_name'),
        ),
    ]
