# Generated by Django 3.0.5 on 2020-04-17 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200417_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='supplier_id',
        ),
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='customer',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customers'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping',
            name='supplier',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Suppliers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customers',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Citys'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='supplier_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Citys'),
        ),
    ]
