# Generated by Django 3.0.4 on 2020-04-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200417_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.CharField(max_length=50),
        ),
    ]
